### ISSUE TITLE
SQS response list or object

### ISSUE THREAD

**Issue by CriztianiX** [umegaya/lua-aws#32]
In SQS 's response, when there are only one message, an object is returned.
But when there are many messages it returns a table with a key "list=true".

This is normal? It should not be a list always?

**Comment by umegaya** [comment]
currently, this is how lua-aws' xml parser works (see https://github.com/umegaya/lua-aws/blob/master/lua-aws/util.lua#L83) when service's protocol type is 'query'. 

sometimes response of aws api which protocol type is "query" contains consequent xml tag with same name, and parser can't determine this is first element of array or single object, because it does not refer to "response shape type", which is declared in  service definition file. 

if I can somehow refer service definition inside of parser in util.lua, then it will be able to return list always when shape type is "list". its doable, but I think this is big change and cannot estimate how all APIs are affected. also take quite some time to fix. 

this behavior is really trouble for you? 

P.S. please consider using following work around.
```
local list = resp.messages.list and resp.messages or {resp.messages}
```
