### ISSUE TITLE
Lists are not parsed correctly in xml shape translator

### ISSUE THREAD

**Issue by mikn** [umegaya/lua-aws#39]
This is because it always descends on .value, whereas lists don't have that parameter. Will send PR, but not sure it'll behave correctly in all cases. :D

**Comment by umegaya** [comment]
hi, thank you for your patch.
could you give me the example API which response actually requires this fix? because: 
1. I think it should be the problem of proper handling of shape definition (in ./services/specs/*.json), so wanna confirm there is no more fundamental problem in the shape code. 
2. if your fix is the proper approach to the problem, need to add test case for it.

**Comment by mikn** [comment]
You can use the ListObjects API for S3 to test. I don't think there's any
problem with the shape definition as just moving the code closer to the JS
library solved the issue for me (now both GetObject and ListObjects works
as expected for me.)
How do I run the tests, by the way? Would be cool if it worked with moto
server (https://github.com/spulec/moto#stand-alone-server-mode)

**Comment by umegaya** [comment]
thanks! I will check the behavior against that API. if you have urgent need to merge this, please notice.  

just run lua(jit) test/*.lua to run test codes. because of my laziness, no test manager exists now and all tests are subject to run with real AWS :<

probably better to use mock AWS server and some test manager (to run test in CI).

**Comment by umegaya** [comment]
hi, sorry for late. I think root problem is the way that xml shape translator handle flattened list shape, as fixed at https://github.com/umegaya/lua-aws/pull/41/commits/f93986ec3c5940ae675afc45a7a7fa4c8e69d015. if you have a time, can you check this branch also fix your problem? 

I also fixes problem of s3 object metadata not stored/loaded correctly.

**Comment by mikn** [comment]
It's completely ok! I'm on holidays right now, but I'll be able to test next week. :) Thank you for having such interest in maintaining this!

**Comment by umegaya** [comment]
I will merge #41 because I think its suitable fix for the problem, 
if you test merged master in your env and still have a problem, feel free to reopen this issue.
