### ISSUE TITLE
use demo for dynamodb.lua  error

### ISSUE THREAD

**Issue by hanks110** [umegaya/lua-aws#42]
use demo for dynamodb.lua  error
message:lua-aws/core.lua:83: application require lfs for fs strictly but cannot

**Comment by umegaya** [comment]
*short answer:*
if you mean test/dynamodb.lua raises error, please check all of following modules are installed. most likely lfs is not installed. 
```
lfs
cURL
socket
ltn12
cjson
```

*long answer:*
because test/dynamodb.lua tests major combination of available plugins, which is listed in lua-aws/engines/available.lua.
```
return {
	http = { "luasocket", "curl" },
	fs = { "lfs", "os" },
	json = { "cjson", "dkjson" },
}
```

this table key means lua-aws/engines/$key, and value table elements mean lua-aws/engines/$key/$element, 
so at least following modules have to be able to require correctly, to run test/dynamodb.lua fine.
``` 
lua-aws/http/luasocket.lua, lua-aws/http/curl.lua
lua-aws/fs/lfs.lua, lua-aws/http/os.lua
lua-aws/json/csjon.lua, lua-aws/json/dkjson.lua
```

and major reason of requiring above files end in failure, is lack of dependent modules.

**Comment by umegaya** [comment]
but you should be able to use dynamodb API only with luasocket or curl being installed. 
fs and json will be complemented with built-in implementation (os.lua for fs and dkjson for json) in lua-aws.

**Comment by umegaya** [comment]
close this issue because of long time no response from reporter. 
@hanks110 feel free to reopen this if it still matters.
